# Generated by Django 5.1.5 on 2025-02-05 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('product_type', models.CharField(blank=True, choices=[('INSTRUMENT', 'Instrument'), ('ACCESSORY', 'Accessory'), ('MUSIC', 'Music')], max_length=10)),
                ('price', models.FloatField(default=0)),
                ('image', models.ImageField(height_field=250, upload_to='', width_field=250)),
                ('date_rec', models.DateTimeField(verbose_name='date received')),
            ],
        ),
    ]
