# Generated by Django 5.1.5 on 2025-02-06 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aria_music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='product_images/'),
        ),
    ]
